name: Deploy to LatinCloud

on:
  push:
    branches:
      - main  # Cambia 'main' si tu rama principal tiene otro nombre

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Copy files to LatinCloud
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H latincloud.com >> ~/.ssh/known_hosts
        rsync -avz -e "ssh -i ~/.ssh/id_rsa" ./ usuario@ip_servidor:/ruta/destino
